 ### Import libraries

In [1]:
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [2]:
# import dataset
df = pd.read_csv('C:/Users/malla/Downloads/Dataset_ATS_v2 (1).csv')
df.head()

,gender,SeniorCitizen,Dependents,tenure,PhoneService,MultipleLines,InternetService,Contract,MonthlyCharges,Churn
0,Female,0,No,1,No,No,DSL,Month-to-month,25,Yes
1,Male,0,No,41,Yes,No,DSL,One year,25,No
2,Female,0,Yes,52,Yes,No,DSL,Month-to-month,19,No
3,Female,0,No,1,Yes,No,DSL,One year,76,Yes
4,Male,0,No,67,Yes,No,Fiber optic,Month-to-month,51,No

In [3]:
# finding the no of columns and rows

df.shape

(7043, 10)

### there are 10 colums and 7043 rows

In [4]:
# Overall information of dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   gender           7043 non-null   object
 1   SeniorCitizen    7043 non-null   int64
 2   Dependents       7043 non-null   object
 3   tenure           7043 non-null   int64
 4   PhoneService     7043 non-null   object
 5   MultipleLines    7043 non-null   object
 6   InternetService  7043 non-null   object
 7   Contract         7043 non-null   object
 8   MonthlyCharges   7043 non-null   int64
 9   Churn            7043 non-null   object
dtypes: int64(3), object(7)
memory usage: 550.4+ KB

In [5]:
# check null vaules in the dataset
df.isna().sum()

gender             0
SeniorCitizen      0
Dependents         0
tenure             0
PhoneService       0
MultipleLines      0
InternetService    0
Contract           0
MonthlyCharges     0
Churn              0
dtype: int64

In [6]:
# Finding numeric variable or columns
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.758768
std         0.368612    24.559481       30.091650
min         0.000000     0.000000       18.000000
25%         0.000000     9.000000       36.000000
50%         0.000000    29.000000       70.000000
75%         0.000000    55.000000       90.000000
max         1.000000    72.000000      119.000000

In [7]:
# Finding catagorical variable or columns

df.describe(include=['object'], exclude=['int64'])

,gender,Dependents,PhoneService,MultipleLines,InternetService,Contract,Churn
count,7043,7043,7043,7043,7043,7043,7043
unique,2,2,2,2,2,3,2
top,Male,No,Yes,No,DSL,Month-to-month,No
freq,3555,4933,6361,4072,3947,3875,5174

### Feature Engineering

In [8]:
# Grouping categorical value in dataset
categorical_columns = df.select_dtypes(include=['object'], exclude=['int64'])
categorical_columns

,gender,Dependents,PhoneService,MultipleLines,InternetService,Contract,Churn
0,Female,No,No,No,DSL,Month-to-month,Yes
1,Male,No,Yes,No,DSL,One year,No
2,Female,Yes,Yes,No,DSL,Month-to-month,No
3,Female,No,Yes,No,DSL,One year,Yes
4,Male,No,Yes,No,Fiber optic,Month-to-month,No
...,...,...,...,...,...,...,...
7038,Male,No,Yes,Yes,DSL,One year,Yes
7039,Female,Yes,Yes,Yes,Fiber optic,One year,No
7040,Male,Yes,Yes,No,DSL,Month-to-month,No
7041,Male,No,Yes,Yes,Fiber optic,Month-to-month,Yes
7042,Male,No,Yes,No,Fiber optic,Two year,No

In [9]:
# finding numeric value in dataset
numerical_columns =  df.select_dtypes(include=['int64'], exclude=['object'])
numerical_columns

      SeniorCitizen  tenure  MonthlyCharges
0                 0       1              25
1                 0      41              25
2                 0      52              19
3                 0       1              76
4                 0      67              51
...             ...     ...             ...
7038              0       1              95
7039              0      23              91
7040              0      12              21
7041              1      12              99
7042              0      26              20

[7043 rows x 3 columns]

### y represents the dependent variable (output) that you want to predict or analyze against your features i.e X

In [10]:
# y is target variable where X is input variable
y = df[['Churn']]
X = df[['gender', 'SeniorCitizen', 'Dependents', 'tenure', 
    'PhoneService', 'MultipleLines', 'InternetService', 
    'Contract', 'MonthlyCharges']]

In [11]:
X

,gender,SeniorCitizen,Dependents,tenure,PhoneService,MultipleLines,InternetService,Contract,MonthlyCharges
0,Female,0,No,1,No,No,DSL,Month-to-month,25
1,Male,0,No,41,Yes,No,DSL,One year,25
2,Female,0,Yes,52,Yes,No,DSL,Month-to-month,19
3,Female,0,No,1,Yes,No,DSL,One year,76
4,Male,0,No,67,Yes,No,Fiber optic,Month-to-month,51
...,...,...,...,...,...,...,...,...,...
7038,Male,0,No,1,Yes,Yes,DSL,One year,95
7039,Female,0,Yes,23,Yes,Yes,Fiber optic,One year,91
7040,Male,0,Yes,12,Yes,No,DSL,Month-to-month,21
7041,Male,1,No,12,Yes,Yes,Fiber optic,Month-to-month,99
7042,Male,0,No,26,Yes,No,Fiber optic,Two year,20

### Encoding is necessary to convert categorical value into numeric value so we can perform calculation

Note: Don't run the cell twice otherwise the code will encode all the values to 0

In [12]:
# Enconding data in dataset
def convert(value):        #function to convert Yes and NO to 1 and 0
    if value == 'Yes':
        return 1
    else:
        return 0

X['Dependents'] = X['Dependents'].apply(convert)         #apply changes to the dataset X
X['PhoneService']= X['PhoneService'].apply(convert)
X['MultipleLines']= X['MultipleLines'].apply(convert)
X.head()

C:\Users\malla\AppData\Local\Temp\ipykernel_3228\2436782701.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Dependents'] = X['Dependents'].apply(convert)
C:\Users\malla\AppData\Local\Temp\ipykernel_3228\2436782701.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['PhoneService']= X['PhoneService'].apply(convert)
C:\Users\malla\AppData\Local\Temp\ipykernel_3228\2436782701.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['MultipleLines']= X['MultipleLines'].apply(convert)

,gender,SeniorCitizen,Dependents,tenure,PhoneService,MultipleLines,InternetService,Contract,MonthlyCharges
0,Female,0,0,1,0,0,DSL,Month-to-month,25
1,Male,0,0,41,1,0,DSL,One year,25
2,Female,0,1,52,1,0,DSL,Month-to-month,19
3,Female,0,0,1,1,0,DSL,One year,76
4,Male,0,0,67,1,0,Fiber optic,Month-to-month,51

### Checking Unique values of catagorical column/ features

In [13]:
# checking the unique values of catagorical columns
for x in ['gender', 'InternetService', 'Contract']:
    print(x, ":", X[x].unique())

gender : ['Female' 'Male']
InternetService : ['DSL' 'Fiber optic']
Contract : ['Month-to-month' 'One year' 'Two year']

### Enconding each features 

Note: Don't run the cell twice otherwise the code will encode all the values to 0

In [14]:
## Encoding gender feature
def convert_gen(value):        #function to convert Male and Female to 1 and 0
    if value == 'Male':
        return 1
    else:
        return 0

X['gender'] = X['gender'].apply(convert_gen)    #apply changes to the dataset X

X.head(10)

C:\Users\malla\AppData\Local\Temp\ipykernel_3228\2826103861.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['gender'] = X['gender'].apply(convert_gen)

,gender,SeniorCitizen,Dependents,tenure,PhoneService,MultipleLines,InternetService,Contract,MonthlyCharges
0,0,0,0,1,0,0,DSL,Month-to-month,25
1,1,0,0,41,1,0,DSL,One year,25
2,0,0,1,52,1,0,DSL,Month-to-month,19
3,0,0,0,1,1,0,DSL,One year,76
4,1,0,0,67,1,0,Fiber optic,Month-to-month,51
5,0,1,0,68,1,1,Fiber optic,Month-to-month,90
6,0,0,1,23,1,1,Fiber optic,Month-to-month,77
7,1,0,1,72,1,0,DSL,Month-to-month,72
8,1,0,0,70,1,1,Fiber optic,Month-to-month,104
9,1,0,0,1,1,0,DSL,One year,19

In [17]:
#Checking gender encodng
X.gender.value_counts()

gender
1    3555
0    3488
Name: count, dtype: int64

In [19]:
# Encoding InternetService

def convert_ser(value):        #function to convert Male and Female to 1 and 0
    if value == 'DSL':
        return 1
    else:
        return 0

X['InternetService'] = X['InternetService'].apply(convert_gen)   #apply changes to the dataset X

X.head(10)

C:\Users\malla\AppData\Local\Temp\ipykernel_3228\927070017.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['InternetService'] = X['InternetService'].apply(convert_gen)

,gender,SeniorCitizen,Dependents,tenure,PhoneService,MultipleLines,InternetService,Contract,MonthlyCharges
0,0,0,0,1,0,0,0,Month-to-month,25
1,1,0,0,41,1,0,0,One year,25
2,0,0,1,52,1,0,0,Month-to-month,19
3,0,0,0,1,1,0,0,One year,76
4,1,0,0,67,1,0,0,Month-to-month,51
5,0,1,0,68,1,1,0,Month-to-month,90
6,0,0,1,23,1,1,0,Month-to-month,77
7,1,0,1,72,1,0,0,Month-to-month,72
8,1,0,0,70,1,1,0,Month-to-month,104
9,1,0,0,1,1,0,0,One year,19

In [21]:
# Encoding Contract
def convert_con(value):        #function to convert Male and Female to 1 and 0
    if value == 'Month-to-month':
        return 0
    if value == "One year":
        return 1
    else:
        return 2

X['Contract'] = X['Contract'].apply(convert_con)   #apply changes to the dataset X

X.head(10)

C:\Users\malla\AppData\Local\Temp\ipykernel_3228\1700196603.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Contract'] = X['Contract'].apply(convert_con)

,gender,SeniorCitizen,Dependents,tenure,PhoneService,MultipleLines,InternetService,Contract,MonthlyCharges
0,0,0,0,1,0,0,0,0,25
1,1,0,0,41,1,0,0,1,25
2,0,0,1,52,1,0,0,0,19
3,0,0,0,1,1,0,0,1,76
4,1,0,0,67,1,0,0,0,51
5,0,1,0,68,1,1,0,0,90
6,0,0,1,23,1,1,0,0,77
7,1,0,1,72,1,0,0,0,72
8,1,0,0,70,1,1,0,0,104
9,1,0,0,1,1,0,0,1,19

In [78]:
X['InternetService'].value_counts()

InternetService
0    7043
Name: count, dtype: int64

In [30]:
y

     Churn
0      Yes
1       No
2       No
3      Yes
4       No
...    ...
7038   Yes
7039    No
7040    No
7041   Yes
7042    No

[7043 rows x 1 columns]

In [31]:
# Encoding churn in y dataset

y['Churn'] = y['Churn'].apply(convert)

C:\Users\malla\AppData\Local\Temp\ipykernel_3228\1281690900.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['Churn'] = y['Churn'].apply(convert)

In [32]:
y

      Churn
0         1
1         0
2         0
3         1
4         0
...     ...
7038      1
7039      0
7040      0
7041      1
7042      0

[7043 rows x 1 columns]

In [36]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   gender           7043 non-null   int64
 1   SeniorCitizen    7043 non-null   int64
 2   Dependents       7043 non-null   int64
 3   tenure           7043 non-null   int64
 4   PhoneService     7043 non-null   int64
 5   MultipleLines    7043 non-null   int64
 6   InternetService  7043 non-null   int64
 7   Contract         7043 non-null   int64
 8   MonthlyCharges   7043 non-null   int64
dtypes: int64(9)
memory usage: 495.3 KB

## Splitting dataset into Training set and Test sets

We splitting our dataset X and y into two groups:

X_train will contain 80% data of X dataset which will be used for training
X_test will contain 20% data of X dataset which will be used for training
y-train will contain 80% data of y dataset which will be used for training
y-test will contain 20% data of y dataset which will be used for training

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [38]:
X_train

,gender,SeniorCitizen,Dependents,tenure,PhoneService,MultipleLines,InternetService,Contract,MonthlyCharges
6084,1,0,0,16,1,1,0,0,20
4388,1,0,1,1,1,0,0,2,81
2840,0,0,1,13,1,0,0,0,20
4674,1,0,0,18,1,0,0,1,20
2362,1,1,0,60,1,0,0,0,72
...,...,...,...,...,...,...,...,...,...
2383,1,0,0,7,1,0,0,0,21
6034,1,0,0,2,1,0,0,1,55
2431,0,0,0,6,1,0,0,0,50
548,0,0,1,8,1,1,0,1,20
6317,0,0,1,4,1,1,0,0,20

## Feature scaling (normalization)

Numerical columns need scaling because larger numbers like  tenure, monthlyCharges don't disproportionately dominate smaller numbers like tenure or binary flags).

Categorical columns need encoding because machine learning algorithmsrequire numbers instead of text strings like "Fiber optic" or "Month-to-month").

In [44]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [45]:
X_train = scaler.fit_transform(X_train)

In [46]:
X_train

array([[ 0.98800239, -0.43918775, -0.65100377, ...,  0.        ,
        -0.83433231, -1.48827915],
       [ 0.98800239, -0.43918775,  1.53608941, ...,  0.        ,
         1.56639712,  0.53375983],
       [-1.0121433 , -0.43918775,  1.53608941, ...,  0.        ,
        -0.83433231, -1.48827915],
       ...,
       [-1.0121433 , -0.43918775, -0.65100377, ...,  0.        ,
        -0.83433231, -0.49383375],
       [-1.0121433 , -0.43918775,  1.53608941, ...,  0.        ,
         0.36603241, -1.48827915],
       [-1.0121433 , -0.43918775,  1.53608941, ...,  0.        ,
        -0.83433231, -1.48827915]], shape=(5634, 9))

### Purpose of Saving the instance of scaler
a. When you .fit_transform() your training data, the scaler learns specific parameters—namely, the mean and standard deviation of each column in your training set.

b.When new, unseen customer data comes in later (or when you evaluate your model on your test set), that new data must be scaled using the exact same mean and standard deviation learned from the training data.

c. Saving the scaler ensures you can load it later using joblib.load('scaler.pkl') to transform new inputs identically.

In [47]:
import joblib
joblib.dump(scaler, "scaler.pkl")     # saves the scaler.pkl file in current working directory

['scaler.pkl']

In [49]:
import os 
os.getcwd() # gives the path of current working directory

'C:\\Users\\malla'

In [50]:
X_test = scaler.fit_transform(X_test)

In [54]:
pd.DataFrame(X_train).to_csv('X_train.csv', index=False)
pd.DataFrame(X_test).to_csv('X_test.csv', index=False)
pd.DataFrame(y_train).to_csv('y_train.csv', index=False)
pd.DataFrame(y_test).to_csv('y_test.csv', index=False)

In [56]:
X

,gender,SeniorCitizen,Dependents,tenure,PhoneService,MultipleLines,InternetService,Contract,MonthlyCharges
0,0,0,0,1,0,0,0,0,25
1,1,0,0,41,1,0,0,1,25
2,0,0,1,52,1,0,0,0,19
3,0,0,0,1,1,0,0,1,76
4,1,0,0,67,1,0,0,0,51
...,...,...,...,...,...,...,...,...,...
7038,1,0,0,1,1,1,0,1,95
7039,0,0,1,23,1,1,0,1,91
7040,1,0,1,12,1,0,0,0,21
7041,1,1,0,12,1,1,0,0,99
7042,1,0,0,26,1,0,0,2,20

In [71]:
df_cleaned.columns

Index(['gender', 'SeniorCitizen', 'Dependents', 'tenure', 'PhoneService',
       'MultipleLines', 'InternetService', 'Contract', 'MonthlyCharges',
       'Churn'],
      dtype='object')

In [59]:
df_cleaned1 = df_cleaned

In [73]:
#scaling df_cleaned1 
scaled_array = scaler.fit_transform(df_cleaned1)

In [75]:
#creating a separated scaled dataset with column name
df_scaled = pd.DataFrame(scaled_array, columns = df_cleaned.columns)

In [76]:
df_scaled

,gender,SeniorCitizen,Dependents,tenure,PhoneService,MultipleLines,InternetService,Contract,MonthlyCharges,Churn
0,-1.009559,-0.439916,-0.654012,-1.277445,-3.054010,-0.854176,0.0,-0.828207,-1.321350,1.663829
1,0.990532,-0.439916,-0.654012,0.351370,0.327438,-0.854176,0.0,0.371271,-1.321350,-0.601023
2,-1.009559,-0.439916,1.529024,0.799294,0.327438,-0.854176,0.0,-0.828207,-1.520755,-0.601023
3,-1.009559,-0.439916,-0.654012,-1.277445,0.327438,-0.854176,0.0,0.371271,0.373593,1.663829
4,0.990532,-0.439916,-0.654012,1.410099,0.327438,-0.854176,0.0,-0.828207,-0.457261,-0.601023
...,...,...,...,...,...,...,...,...,...,...
7038,0.990532,-0.439916,-0.654012,-1.277445,0.327438,1.170719,0.0,0.371271,1.005042,1.663829
7039,-1.009559,-0.439916,1.529024,-0.381597,0.327438,1.170719,0.0,0.371271,0.872106,-0.601023
7040,0.990532,-0.439916,1.529024,-0.829521,0.327438,-0.854176,0.0,-0.828207,-1.454286,-0.601023
7041,0.990532,2.273159,-0.654012,-0.829521,0.327438,1.170719,0.0,-0.828207,1.137979,1.663829
7042,0.990532,-0.439916,-0.654012,-0.259435,0.327438,-0.854176,0.0,1.570749,-1.487520,-0.601023

In [77]:
#Checking unique values in a scaled dataset to find check proportion
for x in df_scaled:
     print(x, ":", df_scaled[x].unique())

gender : [-1.00955867  0.99053183]
SeniorCitizen : [-0.43991649  2.27315869]
Dependents : [-0.65401193  1.5290241 ]
tenure : [-1.27744458  0.35136997  0.79929397  1.41009942  1.45081979 -0.38159658
  1.61370124  1.53226051  0.06632742 -0.17799476 -0.5851984  -0.70735949
 -0.87024095  0.18848851 -0.42231695  0.55497178  0.7585736  -1.11456313
  0.51425142 -0.1372744   0.71785324 -0.21871513  1.12505688 -0.62591876
  0.02560706  1.36937906  1.49154015  1.00289578 -0.99240204 -0.74807986
 -0.30015585 -1.0331224  -0.78880022 -0.54447804  1.08433651 -0.95168167
 -1.19600386 -0.91096131  0.26992924  0.88073469  0.10704778 -0.82952058
 -0.05583367  0.84001433 -0.09655404  0.63641251  0.22920887  1.32865869
 -0.34087622  0.3106496   0.43281069  1.57298088  1.16577724 -0.25943549
  0.39209033 -0.46303731  0.96217542 -1.15528349 -1.07384277  0.92145506
 -1.23672422  0.47353106  1.2064976   1.24721797  0.67713287 -0.50375767
 -0.66663913  0.59569215 -0.01511331  1.28793833  1.04361615  0.14776815
 -1.31816495]
PhoneService : [-3.05401039  0.32743831]
MultipleLines : [-0.85417615  1.17071871]
InternetService : [0.]
Contract : [-0.8282069   0.37127103  1.57074896]
MonthlyCharges : [-1.32134962 -1.52075464  0.37359302 -0.45726121  0.8388714   0.40682719
  0.24065635  1.30414977 -1.48752047  0.63946638  0.67270055  1.00504224
 -0.35755871  0.17418801  0.80563723  0.5065297   1.40385228  0.10771967
 -0.15815369  0.90533974 -0.02521701 -1.4542863   0.97180808  1.33738394
  1.20444726 -0.32432454 -1.15517877  1.63649147  1.10474475  1.07151058
  0.34035885  1.2709156   1.23768143  0.04125133  0.30712469  1.13797892
 -0.95577376  0.87210557  1.43708645  1.03827641  0.57299804 -0.98900793
 -0.49049538 -0.65666623 -1.35458379  0.14095384 -0.39079287 -0.82283708
  0.93857391  1.37061811 -0.6899004   0.44006136  0.00801716  0.20742218
  0.47329553  0.70593472 -1.28811545  0.60623221 -0.22462203 -0.62343206
  0.53976387 -0.29109037  1.47032062  1.17121309 -0.52372955 -0.2578562
  1.73619397 -0.05845118  1.57002313  0.0744855  -0.12491952  1.50355479
  0.77240306 -0.09168535 -0.19138786 -0.42402704  1.66972564  1.53678896
 -1.0222421   1.6032573  -1.05547627 -0.55696372 -1.38781796 -1.22164711
 -0.75636874  1.7029598  -1.18841294  0.27389052  0.73916889 -0.85607125
 -0.88930542 -1.08871043  1.76942814  1.80266231 -1.1219446  -0.78960291
 -0.72313457 -1.25488128 -0.59019789 -0.92253959 -1.55398881]
Churn : [ 1.66382851 -0.60102348]

In [82]:
pd.DataFrame(df_scaled).to_csv('df_scaled.csv', index=False)

In [81]:
os.getcwd()

'C:\\Users\\malla'